# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1958c8404bca43c911fcb45e77570f07c0c21502ba6c27b72bdf4f217073ce34399cf97311e3299e9fd8c696bc70f14dd78b2664c64aaf2a47fc78be958dfa6

test:
  secret_key_base: 6d5c448ab153e28d420a455121c9fd6b30ee2ed724899bb3cbce8b0214c8f8fe123525acd85312292786af6a54cedd8f576afe1309ccebab50eff29f21b14154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
